"""Final revision

Revision ID: f1ef06c0b196
Revises: a49cd54c265b
Create Date: 2022-05-04 22:33:00.043230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ef06c0b196'
down_revision = 'a49cd54c265b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
